version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: pme_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  duckdb:
    image: ghcr.io/duckdb/duckdb:latest
    volumes:
      - duckdb-data:/data

  worker:
    build: .
    command: celery -A pme_calculator.backend.worker.tasks worker --loglevel=info
    volumes:
      - .:/app
      - duckdb-data:/data
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DUCKDB_PATH=/data/pme.duckdb

  beat:
    build: .
    command: celery -A pme_calculator.backend.worker.tasks beat --loglevel=info
    volumes:
      - .:/app
      - duckdb-data:/data
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DUCKDB_PATH=/data/pme.duckdb

volumes:
  redis_data:
    driver: local
  duckdb-data: 