name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - run: ruff check .
      - run: black --check .
      - run: pytest -q 