name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run ruff linting
        run: ruff check .
        continue-on-error: true
      - name: Run black formatting check
        run: black --check .
        continue-on-error: true
      - name: Run tests
        run: pytest -q --tb=short 